### ISSUE TITLE
抛出这种错误

### ISSUE THREAD

**Issue by lkyuier** [FoloToy/folotoy-server-self-hosting#114]
docker logs -f folotoy-folotoy-1
2024-01-22 15:17:37,732 - INFO - FoloToy Server Version: v23.50.1.4-beta
2024-01-22 15:17:37,743 - ERROR - Run error: [Errno 111] Connection refused
Traceback (most recent call last):
  File "core/folotoy_app.py", line 126, in core.folotoy_app.FolotoyApp.start
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 914, in connect
    return self.reconnect()
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 1044, in reconnect
    sock = self._create_socket_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/socket.py", line 851, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.11/socket.py", line 836, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

**Comment by lewangdev** [comment]
emqx没有启动起来，emqx启动比较慢，稍等再看看日志

**Comment by lkyuier** [comment]
rrno 111] Connection refused
2024-01-22 15:17:43,754 - INFO - Sleep 2s to reconnect
2024-01-22 15:17:45,756 - INFO - Speech server started(0.0.0.0:8085/udp)
2024-01-22 15:17:45,757 - INFO - Connected to MQTT Broker(emqx:1883)!  这样是不是意味着emqx起来了？？

**Comment by lkyuier** [comment]
docker logs  -f folotoy-emqx-1
WARNING: Default (insecure) Erlang cookie is in use.
WARNING: Configure node.cookie in /opt/emqx/etc/emqx.conf or override from environment variable EMQX_NODE__COOKIE
WARNING: NOTE: Use the same cookie for all nodes in the cluster.
EMQX_RPC__PORT_DISCOVERY [rpc.port_discovery]: manual
EMQX_NODE__NAME [node.name]: emqx@172.19.0.2
Listener ssl:default on 0.0.0.0:8883 started.
Listener tcp:default on 0.0.0.0:1883 started.
Listener ws:default on 0.0.0.0:8083 started.
Listener wss:default on 0.0.0.0:8084 started.
Listener http:dashboard on :18083 started.
EMQX 5.4.1 is running now!
2024-01-22T07:18:45.010000+00:00 [warning] msg: alarm_is_activated, mfa: emqx_alarm:do_actions/3(418), message: <<"71.01% mem usage">>, name: high_system_memory_usage
2024-01-22T07:33:45.081456+00:00 [warning] msg: alarm_is_deactivated, mfa: emqx_alarm:do_actions/3(424), name: high_system_memory_usage  ,王哥，我看我按对话没啥反应，是为什么？
