### ISSUE TITLE
不能STT

### ISSUE THREAD

**Issue by 54dashayu** [FoloToy/folotoy-server-self-hosting#122]
Docker启动后的日志：
`2024-03-01 01:04:50 nginx-1    | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
2024-03-01 01:04:50 nginx-1    | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
2024-03-01 01:04:50 nginx-1    | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
2024-03-01 01:04:50 nginx-1    | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
2024-03-01 01:04:50 nginx-1    | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
2024-03-01 01:04:50 nginx-1    | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
2024-03-01 01:04:50 nginx-1    | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
2024-03-01 01:04:50 nginx-1    | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
2024-03-01 01:04:50 nginx-1    | /docker-entrypoint.sh: Configuration complete; ready for start up
2024-03-01 01:04:50 nginx-1    | 2024/02/29 17:04:50 [notice] 1#1: using the "epoll" event method
2024-03-01 01:04:50 nginx-1    | 2024/02/29 17:04:50 [notice] 1#1: nginx/1.25.4
2024-03-01 01:04:50 nginx-1    | 2024/02/29 17:04:50 [notice] 1#1: built by gcc 12.2.0 (Debian 12.2.0-14) 
2024-03-01 01:04:50 nginx-1    | 2024/02/29 17:04:50 [notice] 1#1: OS: Linux 5.15.146.1-microsoft-standard-WSL2
2024-03-01 01:04:50 nginx-1    | 2024/02/29 17:04:50 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2024-03-01 01:04:50 nginx-1    | 2024/02/29 17:04:50 [notice] 1#1: start worker processes
2024-03-01 01:04:50 nginx-1    | 2024/02/29 17:04:50 [notice] 1#1: start worker process 29
2024-03-01 01:04:50 nginx-1    | 2024/02/29 17:04:50 [notice] 1#1: start worker process 30
2024-03-01 01:04:50 nginx-1    | 2024/02/29 17:04:50 [notice] 1#1: start worker process 31
2024-03-01 01:04:50 nginx-1    | 2024/02/29 17:04:50 [notice] 1#1: start worker process 32
2024-03-01 01:04:50 nginx-1    | 2024/02/29 17:04:50 [notice] 1#1: start worker process 33
2024-03-01 01:04:50 nginx-1    | 2024/02/29 17:04:50 [notice] 1#1: start worker process 34
2024-03-01 01:04:50 nginx-1    | 2024/02/29 17:04:50 [notice] 1#1: start worker process 35
2024-03-01 01:04:50 nginx-1    | 2024/02/29 17:04:50 [notice] 1#1: start worker process 36
2024-03-01 01:04:51 folotoy-1  | /usr/local/lib/python3.11/site-packages/pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
2024-03-01 01:04:51 folotoy-1  |   warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
2024-03-01 01:04:52 folotoy-1  | 2024-03-01 01:04:52,208 - INFO - FoloToy Server Version: v24.7.1.3-beta
2024-03-01 01:04:52 folotoy-1  | 2024-03-01 01:04:52,210 - ERROR - Run error: [Errno 111] Connection refused
2024-03-01 01:04:52 folotoy-1  | Traceback (most recent call last):
2024-03-01 01:04:52 folotoy-1  |   File "core/folotoy_app.py", line 126, in core.folotoy_app.FolotoyApp.start
2024-03-01 01:04:52 folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 914, in connect
2024-03-01 01:04:52 folotoy-1  |     return self.reconnect()
2024-03-01 01:04:52 folotoy-1  |            ^^^^^^^^^^^^^^^^
2024-03-01 01:04:52 folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 1044, in reconnect
2024-03-01 01:04:52 folotoy-1  |     sock = self._create_socket_connection()
2024-03-01 01:04:52 folotoy-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-01 01:04:52 folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
2024-03-01 01:04:52 folotoy-1  |     return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
2024-03-01 01:04:52 folotoy-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-01 01:04:52 folotoy-1  |   File "/usr/local/lib/python3.11/socket.py", line 851, in create_connection
2024-03-01 01:04:52 folotoy-1  |     raise exceptions[0]
2024-03-01 01:04:52 folotoy-1  |   File "/usr/local/lib/python3.11/socket.py", line 836, in create_connection
2024-03-01 01:04:52 folotoy-1  |     sock.connect(sa)
2024-03-01 01:04:52 folotoy-1  | ConnectionRefusedError: [Errno 111] Connection refused
2024-03-01 01:04:52 folotoy-1  | 2024-03-01 01:04:52,212 - INFO - Sleep 2s to reconnect
2024-03-01 01:04:52 emqx-1     | WARNING: Default (insecure) Erlang cookie is in use.
2024-03-01 01:04:52 emqx-1     | WARNING: Configure node.cookie in /opt/emqx/etc/emqx.conf or override from environment variable EMQX_NODE__COOKIE
2024-03-01 01:04:52 emqx-1     | WARNING: NOTE: Use the same cookie for all nodes in the cluster.
2024-03-01 01:04:54 folotoy-1  | 2024-03-01 01:04:54,213 - ERROR - Run error: [Errno 111] Connection refused
2024-03-01 01:04:54 folotoy-1  | Traceback (most recent call last):
2024-03-01 01:04:54 folotoy-1  |   File "core/folotoy_app.py", line 126, in core.folotoy_app.FolotoyApp.start
2024-03-01 01:04:54 folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 914, in connect
2024-03-01 01:04:54 folotoy-1  |     return self.reconnect()
2024-03-01 01:04:54 folotoy-1  |            ^^^^^^^^^^^^^^^^
2024-03-01 01:04:54 folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 1044, in reconnect
2024-03-01 01:04:54 folotoy-1  |     sock = self._create_socket_connection()
2024-03-01 01:04:54 folotoy-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-01 01:04:54 folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
2024-03-01 01:04:54 folotoy-1  |     return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
2024-03-01 01:04:54 folotoy-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-01 01:04:54 folotoy-1  |   File "/usr/local/lib/python3.11/socket.py", line 851, in create_connection
2024-03-01 01:04:54 folotoy-1  |     raise exceptions[0]
2024-03-01 01:04:54 folotoy-1  |   File "/usr/local/lib/python3.11/socket.py", line 836, in create_connection
2024-03-01 01:04:54 folotoy-1  |     sock.connect(sa)
2024-03-01 01:04:54 folotoy-1  | ConnectionRefusedError: [Errno 111] Connection refused
2024-03-01 01:04:54 folotoy-1  | 2024-03-01 01:04:54,214 - INFO - Sleep 2s to reconnect
2024-03-01 01:04:56 folotoy-1  | 2024-03-01 01:04:56,220 - ERROR - Run error: [Errno 111] Connection refused
2024-03-01 01:04:56 folotoy-1  | Traceback (most recent call last):
2024-03-01 01:04:56 folotoy-1  |   File "core/folotoy_app.py", line 126, in core.folotoy_app.FolotoyApp.start
2024-03-01 01:04:56 folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 914, in connect
2024-03-01 01:04:56 folotoy-1  |     return self.reconnect()
2024-03-01 01:04:56 folotoy-1  |            ^^^^^^^^^^^^^^^^
2024-03-01 01:04:56 folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 1044, in reconnect
2024-03-01 01:04:56 folotoy-1  |     sock = self._create_socket_connection()
2024-03-01 01:04:56 folotoy-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-01 01:04:56 folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
2024-03-01 01:04:56 folotoy-1  |     return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
2024-03-01 01:04:56 folotoy-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-01 01:04:56 folotoy-1  |   File "/usr/local/lib/python3.11/socket.py", line 851, in create_connection
2024-03-01 01:04:56 folotoy-1  |     raise exceptions[0]
2024-03-01 01:04:56 folotoy-1  |   File "/usr/local/lib/python3.11/socket.py", line 836, in create_connection
2024-03-01 01:04:56 folotoy-1  |     sock.connect(sa)
2024-03-01 01:04:56 folotoy-1  | ConnectionRefusedError: [Errno 111] Connection refused
2024-03-01 01:04:56 folotoy-1  | 2024-03-01 01:04:56,234 - INFO - Sleep 2s to reconnect
2024-03-01 01:04:57 emqx-1     | EMQX_RPC__PORT_DISCOVERY [rpc.port_discovery]: manual
2024-03-01 01:04:57 emqx-1     | EMQX_NODE__NAME [node.name]: emqx@node1.emqx.io
2024-03-01 01:04:58 folotoy-1  | 2024-03-01 01:04:58,235 - ERROR - Run error: [Errno 111] Connection refused
2024-03-01 01:04:58 folotoy-1  | Traceback (most recent call last):
2024-03-01 01:04:58 folotoy-1  |   File "core/folotoy_app.py", line 126, in core.folotoy_app.FolotoyApp.start
2024-03-01 01:04:58 folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 914, in connect
2024-03-01 01:04:58 folotoy-1  |     return self.reconnect()
2024-03-01 01:04:58 folotoy-1  |            ^^^^^^^^^^^^^^^^
2024-03-01 01:04:58 folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 1044, in reconnect
2024-03-01 01:04:58 folotoy-1  |     sock = self._create_socket_connection()
2024-03-01 01:04:58 folotoy-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-01 01:04:58 folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
2024-03-01 01:04:58 folotoy-1  |     return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
2024-03-01 01:04:58 folotoy-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-01 01:04:58 folotoy-1  |   File "/usr/local/lib/python3.11/socket.py", line 851, in create_connection
2024-03-01 01:04:58 folotoy-1  |     raise exceptions[0]
2024-03-01 01:04:58 folotoy-1  |   File "/usr/local/lib/python3.11/socket.py", line 836, in create_connection
2024-03-01 01:04:58 folotoy-1  |     sock.connect(sa)
2024-03-01 01:04:58 folotoy-1  | ConnectionRefusedError: [Errno 111] Connection refused
2024-03-01 01:04:58 folotoy-1  | 2024-03-01 01:04:58,236 - INFO - Sleep 2s to reconnect
2024-03-01 01:05:00 folotoy-1  | 2024-03-01 01:05:00,237 - ERROR - Run error: [Errno 111] Connection refused
2024-03-01 01:05:00 folotoy-1  | Traceback (most recent call last):
2024-03-01 01:05:00 folotoy-1  |   File "core/folotoy_app.py", line 126, in core.folotoy_app.FolotoyApp.start
2024-03-01 01:05:00 folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 914, in connect
2024-03-01 01:05:00 folotoy-1  |     return self.reconnect()
2024-03-01 01:05:00 folotoy-1  |            ^^^^^^^^^^^^^^^^
2024-03-01 01:05:00 folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 1044, in reconnect
2024-03-01 01:05:00 folotoy-1  |     sock = self._create_socket_connection()
2024-03-01 01:05:00 folotoy-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-01 01:05:00 folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
2024-03-01 01:05:00 folotoy-1  |     return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
2024-03-01 01:05:00 folotoy-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-01 01:05:00 folotoy-1  |   File "/usr/local/lib/python3.11/socket.py", line 851, in create_connection
2024-03-01 01:05:00 folotoy-1  |     raise exceptions[0]
2024-03-01 01:05:00 folotoy-1  |   File "/usr/local/lib/python3.11/socket.py", line 836, in create_connection
2024-03-01 01:05:00 folotoy-1  |     sock.connect(sa)
2024-03-01 01:05:00 folotoy-1  | ConnectionRefusedError: [Errno 111] Connection refused
2024-03-01 01:05:00 folotoy-1  | 2024-03-01 01:05:00,237 - INFO - Sleep 2s to reconnect
2024-03-01 01:05:00 emqx-1     | Listener ssl:default on 0.0.0.0:8883 started.
2024-03-01 01:05:00 emqx-1     | Listener tcp:default on 0.0.0.0:1883 started.
2024-03-01 01:05:00 emqx-1     | Listener ws:default on 0.0.0.0:8083 started.
2024-03-01 01:05:00 emqx-1     | Listener wss:default on 0.0.0.0:8084 started.
2024-03-01 01:05:01 emqx-1     | Listener http:dashboard on :18083 started.
2024-03-01 01:05:01 emqx-1     | EMQX 5.5.0 is running now!
2024-03-01 01:05:02 folotoy-1  | 2024-03-01 01:05:02,242 - INFO - Speech server started(0.0.0.0:8085/udp)
2024-03-01 01:05:02 folotoy-1  | 2024-03-01 01:05:02,252 - INFO - Connected to MQTT Broker(emqx:1883)!
2024-03-01 01:05:19 folotoy-1  | 2024-03-01 01:05:19,384 - DEBUG - Received /user/folotoy/24dcc3d09b90/thing/event/post: message data: {'msgId': 0, 'identifier': 'login', 'outParams': {'role': 7}}
2024-03-01 01:05:19 folotoy-1  | 2024-03-01 01:05:19,384 - DEBUG - Publish topic: /user/folotoy/24dcc3d09b90/thing/command/call, msg: {"msgId": 0, "identifier": "updatetoken", "inputParams": {"token": "db7c4a7d9926467a8b182c1f32b15f06"}}
2024-03-01 01:05:19 folotoy-1  | 2024-03-01 01:05:19,384 - DEBUG - Publish topic: /user/folotoy/24dcc3d09b90/thing/command/call, msg: {"msgId": 1, "identifier": "updateconfig", "inputParams": {"speechUdpServerHost": "192.168.100.108", "speechUdpServerPort": 8085}}
2024-03-01 01:05:35 folotoy-1  | 2024-03-01 01:05:35,882 - DEBUG - Received /user/folotoy/24dcc3d09b90/thing/event/post: message data: {'msgId': 0, 'identifier': 'login', 'outParams': {'role': 7}}
2024-03-01 01:05:35 folotoy-1  | 2024-03-01 01:05:35,882 - DEBUG - Publish topic: /user/folotoy/24dcc3d09b90/thing/command/call, msg: {"msgId": 0, "identifier": "updatetoken", "inputParams": {"token": "495b08b68e1a4c13a10db39c9b7ca0c9"}}
2024-03-01 01:05:35 folotoy-1  | 2024-03-01 01:05:35,883 - DEBUG - Publish topic: /user/folotoy/24dcc3d09b90/thing/command/call, msg: {"msgId": 1, "identifier": "updateconfig", "inputParams": {"speechUdpServerHost": "192.168.100.108", "speechUdpServerPort": 8085}}
2024-03-01 01:05:42 folotoy-1  | 2024-03-01 01:05:42,391 - DEBUG - Received /user/folotoy/24dcc3d09b90/thing/command/callAck: message data: {'msgId': 0, 'identifier': 'updatetoken', 'result': 1}
2024-03-01 01:05:42 folotoy-1  | 2024-03-01 01:05:42,391 - DEBUG - Command call ack: True, topic_tokens: {'#': [], '+': ['24dcc3d09b90']}
2024-03-01 01:05:44 folotoy-1  | 2024-03-01 01:05:44,217 - DEBUG - Received /user/folotoy/24dcc3d09b90/thing/command/callAck: message data: {'msgId': 1, 'identifier': 'updateconfig', 'result': 1}
2024-03-01 01:05:44 folotoy-1  | 2024-03-01 01:05:44,217 - DEBUG - Command call ack: True, topic_tokens: {'#': [], '+': ['24dcc3d09b90']}
2024-03-01 01:05:44 folotoy-1  | 2024-03-01 01:05:44,289 - DEBUG - Received /user/folotoy/24dcc3d09b90/thing/event/post: message data: {'msgId': 1, 'identifier': 'press_small_btn', 'outParams': {'keyCode': 7, 'changed': 1}}
2024-03-01 01:05:44 folotoy-1  | 2024-03-01 01:05:44,290 - DEBUG - Using selector: EpollSelector
2024-03-01 01:05:46 folotoy-1  | 2024-03-01 01:05:46,371 - DEBUG - TTS(edge-tts) request time cost: 2.08s
2024-03-01 01:05:46 folotoy-1  | 2024-03-01 01:05:46,377 - DEBUG - Publish topic: /user/folotoy/24dcc3d09b90/thing/command/call, msg: {"msgId": 2, "identifier": "updatestartvoice", "inputParams": {"url": "http://192.168.100.108:8082/voice-52f7caa241a54267a57a6126a15ee118.mp3", "keyCode": 7, "etag": "70363c2fc658f9dcd53e71df1c90d048"}}
2024-03-01 01:05:49 folotoy-1  | 2024-03-01 01:05:49,319 - DEBUG - Received /user/folotoy/24dcc3d09b90/thing/command/callAck: message data: {'msgId': 2, 'identifier': 'updatestartvoice', 'result': 1}
2024-03-01 01:05:49 folotoy-1  | 2024-03-01 01:05:49,319 - DEBUG - Command call ack: True, topic_tokens: {'#': [], '+': ['24dcc3d09b90']}
`

**Comment by lewangdev** [comment]
WARNING - Unknown sst type found: Azure STT

stt type 配置错误，参考一下文档中的值
