### ISSUE TITLE
TTS好像有問題 ，八爪魚機板都無對話反應

### ISSUE THREAD

**Issue by black316h** [FoloToy/folotoy-server-self-hosting#149]
File "core/folotoy_app.py", line 126, in core.folotoy_app.FolotoyApp.start
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 914, in connect
    return self.reconnect()
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 1044, in reconnect
    sock = self._create_socket_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/socket.py", line 851, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.11/socket.py", line 836, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
2024-04-07 01:55:03,050 - INFO - Sleep 2s to reconnect
2024-04-07 01:55:05,052 - ERROR - Run error: [Errno 111] Connection refused
Traceback (most recent call last):
  File "core/folotoy_app.py", line 126, in core.folotoy_app.FolotoyApp.start
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 914, in connect
    return self.reconnect()
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 1044, in reconnect
    sock = self._create_socket_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/socket.py", line 851, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.11/socket.py", line 836, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
2024-04-07 01:55:05,052 - INFO - Sleep 2s to reconnect
2024-04-07 01:55:07,201 - INFO - Speech server started(0.0.0.0:8085/udp)
2024-04-07 01:55:07,223 - INFO - Connected to MQTT Broker(emqx:1883)!
2024-04-07 01:55:12,061 - DEBUG - Received /user/folotoy/24dcc3cf370c/thing/event/post: message data: {'msgId': 3, 'identifier': 'login', 'outParams': {'role': 6}}
2024-04-07 01:55:12,063 - DEBUG - Publish topic: /user/folotoy/24dcc3cf370c/thing/command/call, msg: {"msgId": 0, "identifier": "updatetoken", "inputParams": {"token": "37c41154796646a28ccf3bd06fc87364"}}
2024-04-07 01:55:12,063 - DEBUG - Publish topic: /user/folotoy/24dcc3cf370c/thing/command/call, msg: {"msgId": 1, "identifier": "updateconfig", "inputParams": {"speechUdpServerHost": "47.236.245.175", "speechUdpServerPort": 8085}}
2024-04-07 01:55:15,013 - DEBUG - Received /user/folotoy/24dcc3cf370c/thing/command/callAck: message data: {'msgId': 0, 'identifier': 'updatetoken', 'result': 1}
2024-04-07 01:55:15,013 - DEBUG - Command call ack: True, topic_tokens: {'#': [], '+': ['24dcc3cf370c']}
2024-04-07 01:55:15,558 - DEBUG - Received /user/folotoy/24dcc3cf370c/thing/command/callAck: message data: {'msgId': 1, 'identifier': 'updateconfig', 'result': 1}
2024-04-07 01:55:15,558 - DEBUG - Command call ack: True, topic_tokens: {'#': [], '+': ['24dcc3cf370c']}
2024-04-07 01:55:15,631 - DEBUG - Received /user/folotoy/24dcc3cf370c/thing/event/post: message data: {'msgId': 4, 'identifier': 'press_small_btn', 'outParams': {'keyCode': 6, 'changed': 0}}
2024-04-07 01:55:15,632 - DEBUG - Role no changed, empty the messages
2024-04-07 01:55:35,865 - DEBUG - Received /user/folotoy/24dcc3cf370c/thing/event/post: message data: {'msgId': 5, 'identifier': 'press_small_btn', 'outParams': {'keyCode': 7, 'changed': 1}}
2024-04-07 01:55:35,902 - DEBUG - Request received. Product:None Endpoint:nls-meta.cn-shanghai.aliyuncs.com Params: {'Version': '2019-02-28', 'Action': 'CreateToken', 'Format': 'JSON', 'RegionId': 'cn-shanghai', 'Timestamp': '2024-04-06T17:55:35Z', 'SignatureMethod': 'HMAC-SHA1', 'SignatureType': '', 'SignatureVersion': '1.0', 'SignatureNonce': '885fbd2d-bd33-4dca-82c7-5381012980ab', 'Signature': 'go4aD6TikVT7Lx+gi8rlTosHzoE='}
2024-04-07 01:55:36,389 - DEBUG - Response received. Product:None Response-body: b'{"ErrMsg":"","Token":{"UserId":"5963112160688087","Id":"3dc3e63f48144726b5b518d5abd79e29","ExpireTime":1712555736}}'
2024-04-07 01:55:36,390 - DEBUG - b'{"ErrMsg":"","Token":{"UserId":"5963112160688087","Id":"3dc3e63f48144726b5b518d5abd79e29","ExpireTime":1712555736}}'
2024-04-07 01:55:36,390 - DEBUG - token = 3dc3e63f48144726b5b518d5abd79e29, expire time = 1712555736
2024-04-07 01:55:36,395 - DEBUG - Starting new HTTPS connection (1): nls-gateway-cn-shanghai.aliyuncs.com:443
2024-04-07 01:55:37,023 - DEBUG - https://nls-gateway-cn-shanghai.aliyuncs.com:443 "POST /stream/v1/tts HTTP/1.1" 400 128
2024-04-07 01:55:37,024 - WARNING - TTS(openai-tts) request failed: {"task_id":"43e9c85d650248378d4010b7ef4b6398","result":"","status":40020105,"message":"Meta:APPKEY_NOT_EXIST:Appkey not exist!"}, payload: {'appkey': 'e0K2F7oETTEkg11W', 'text': '你好，我是小兔，请问有什么我可以帮助你的吗？', 'format': 'mp3'}
2024-04-07 01:56:27,079 - DEBUG - Received /user/folotoy/24dcc3cf370c/thing/event/post: message data: {'msgId': 6, 'identifier': 'press_small_btn', 'outParams': {'keyCode': 1, 'changed': 1}}
2024-04-07 01:56:27,082 - DEBUG - Starting new HTTPS connection (1): nls-gateway-cn-shanghai.aliyuncs.com:443
2024-04-07 01:56:27,658 - DEBUG - https://nls-gateway-cn-shanghai.aliyuncs.com:443 "POST /stream/v1/tts HTTP/1.1" 400 128
2024-04-07 01:56:27,659 - WARNING - TTS(openai-tts) request failed: {"task_id":"95e6c3a4f4e342eb8fa1d0d950ff00df","result":"","status":40020105,"message":"Meta:APPKEY_NOT_EXIST:Appkey not exist!"}, payload: {'appkey': 'e0K2F7oETTEkg11W', 'text': '你好，我是陪伴兔，请问有什么我可以帮助你的吗？', 'format': 'mp3'}
2024-04-07 01:56:32,104 - DEBUG - Received /user/folotoy/24dcc3cf370c/thing/event/post: message data: {'msgId': 7, 'identifier': 'press_small_btn', 'outParams': {'keyCode': 7, 'changed': 1}}
2024-04-07 01:56:32,107 - DEBUG - Starting new HTTPS connection (1): nls-gateway-cn-shanghai.aliyuncs.com:443
2024-04-07 01:56:32,739 - DEBUG - https://nls-gateway-cn-shanghai.aliyuncs.com:443 "POST /stream/v1/tts HTTP/1.1" 400 128
2024-04-07 01:56:32,740 - WARNING - TTS(openai-tts) request failed: {"task_id":"6e4af89def234c8fbe88ed410264ef2a","result":"","status":40020105,"message":"Meta:APPKEY_NOT_EXIST:Appkey not exist!"}, payload: {'appkey': 'e0K2F7oETTEkg11W', 'text': '你好，我是小兔，请问有什么我可以帮助你的吗？', 'format': 'mp3'}
2024-04-07 01:56:43,423 - DEBUG - Received /user/folotoy/24dcc3cf370c/thing/event/post: message data: {'msgId': 0, 'identifier': 'login', 'outParams': {'role': 5}}
2024-04-07 01:56:43,424 - DEBUG - Publish topic: /user/folotoy/24dcc3cf370c/thing/command/call, msg: {"msgId": 0, "identifier": "updatetoken", "inputParams": {"token": "31460e0bb6634d4195180fff082c7f05"}}
2024-04-07 01:56:43,424 - DEBUG - Publish topic: /user/folotoy/24dcc3cf370c/thing/command/call, msg: {"msgId": 1, "identifier": "updateconfig", "inputParams": {"speechUdpServerHost": "47.236.245.175", "speechUdpServerPort": 8085}}
2024-04-07 01:56:44,377 - DEBUG - Received /user/folotoy/24dcc3cf370c/thing/command/callAck: message data: {'msgId': 0, 'identifier': 'updatetoken', 'result': 1}
2024-04-07 01:56:44,377 - DEBUG - Command call ack: True, topic_tokens: {'#': [], '+': ['24dcc3cf370c']}
2024-04-07 01:56:45,889 - DEBUG - Received /user/folotoy/24dcc3cf370c/thing/command/callAck: message data: {'msgId': 1, 'identifier': 'updateconfig', 'result': 1}
2024-04-07 01:56:45,889 - DEBUG - Command call ack: True, topic_tokens: {'#': [], '+': ['24dcc3cf370c']}
2024-04-07 01:56:45,957 - DEBUG - Received /user/folotoy/24dcc3cf370c/thing/event/post: message data: {'msgId': 1, 'identifier': 'press_small_btn', 'outParams': {'keyCode': 5, 'changed': 1}}
2024-04-07 01:56:45,959 - DEBUG - Starting new HTTPS connection (1): nls-gateway-cn-shanghai.aliyuncs.com:443
2024-04-07 01:56:46,565 - DEBUG - https://nls-gateway-cn-shanghai.aliyuncs.com:443 "POST /stream/v1/tts HTTP/1.1" 400 128
2024-04-07 01:56:46,566 - WARNING - TTS(openai-tts) request failed: {"task_id":"ab17317a1b4a4444843ad9394f7f21a4","result":"","status":40020105,"message":"Meta:APPKEY_NOT_EXIST:Appkey not exist!"}, payload: {'appkey': 'e0K2F7oETTEkg11W', 'text': '你好，我是口算兔，我们一起来玩玩口算游戏吧？', 'format': 'mp3'}
2024-04-07 01:57:02,294 - DEBUG - Received /user/folotoy/24dcc3cf370c/thing/event/post: message data: {'msgId': 2, 'identifier': 'press_small_btn', 'outParams': {'keyCode': 6, 'changed': 1}}
2024-04-07 01:57:02,296 - DEBUG - Starting new HTTPS connection (1): nls-gateway-cn-shanghai.aliyuncs.com:443
2024-04-07 01:57:02,991 - DEBUG - https://nls-gateway-cn-shanghai.aliyuncs.com:443 "POST /stream/v1/tts HTTP/1.1" 400 128
2024-04-07 01:57:02,992 - WARNING - TTS(openai-tts) request failed: {"task_id":"9942aab55e1147bf9099d8e0d2c200d0","result":"","status":40020105,"message":"Meta:APPKEY_NOT_EXIST:Appkey not exist!"}, payload: {'appkey': 'e0K2F7oETTEkg11W', 'text': '你好，我是台湾兔，请问有什么我可以帮助你的吗？', 'format': 'mp3'}
2024-04-07 01:57:34,124 - INFO - [folotoy] Connection is disconnect,return code=7
2024-04-07 01:57:49,166 - INFO - Connected to MQTT Broker(emqx:1883)!
/usr/local/lib/python3.11/site-packages/pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
2024-04-07 01:57:55,327 - INFO - FoloToy Server Version: v24.7.1.3-beta
2024-04-07 01:57:55,338 - INFO - Speech server started(0.0.0.0:8085/udp)
2024-04-07 01:57:55,339 - INFO - Connected to MQTT Broker(emqx:1883)!
2024-04-07 01:58:05,908 - DEBUG - Received /user/folotoy/24dcc3cf370c/thing/event/post: message data: {'msgId': 3, 'identifier': 'login', 'outParams': {'role': 6}}
2024-04-07 01:58:05,908 - DEBUG - Publish topic: /user/folotoy/24dcc3cf370c/thing/command/call, msg: {"msgId": 0, "identifier": "updatetoken", "inputParams": {"token": "15722b596fbe46138a9004da903614c2"}}
2024-04-07 01:58:05,908 - DEBUG - Publish topic: /user/folotoy/24dcc3cf370c/thing/command/call, msg: {"msgId": 1, "identifier": "updateconfig", "inputParams": {"speechUdpServerHost": "47.236.245.175", "speechUdpServerPort": 8085}}
2024-04-07 01:58:08,861 - DEBUG - Received /user/folotoy/24dcc3cf370c/thing/command/callAck: message data: {'msgId': 0, 'identifier': 'updatetoken', 'result': 1}
2024-04-07 01:58:08,861 - DEBUG - Command call ack: True, topic_tokens: {'#': [], '+': ['24dcc3cf370c']}
2024-04-07 01:58:09,379 - DEBUG - Received /user/folotoy/24dcc3cf370c/thing/command/callAck: message data: {'msgId': 1, 'identifier': 'updateconfig', 'result': 1}
2024-04-07 01:58:09,379 - DEBUG - Command call ack: True, topic_tokens: {'#': [], '+': ['24dcc3cf370c']}
2024-04-07 01:58:09,447 - DEBUG - Received /user/folotoy/24dcc3cf370c/thing/event/post: message data: {'msgId': 4, 'identifier': 'press_small_btn', 'outParams': {'keyCode': 6, 'changed': 0}}
2024-04-07 01:58:09,447 - DEBUG - Role no changed, empty the messages
2024-04-07 01:59:03,319 - DEBUG - Received /user/folotoy/24dcc3cf370c/thing/event/post: message data: {'msgId': 5, 'identifier': 'press_small_btn', 'outParams': {'keyCode': 7, 'changed': 1}}
2024-04-07 01:59:03,325 - DEBUG - Request received. Product:None Endpoint:nls-meta.cn-shanghai.aliyuncs.com Params: {'Version': '2019-02-28', 'Action': 'CreateToken', 'Format': 'JSON', 'RegionId': 'cn-shanghai', 'Timestamp': '2024-04-06T17:59:03Z', 'SignatureMethod': 'HMAC-SHA1', 'SignatureType': '', 'SignatureVersion': '1.0', 'SignatureNonce': 'b89b9fbc-1f6a-4972-9b99-e7943cf1d170', 'Signature': 'RFLuh9l5xtjebEONUh38+VpUAjc='}
2024-04-07 01:59:03,762 - DEBUG - Response received. Product:None Response-body: b'{"ErrMsg":"","Token":{"UserId":"5963112160688087","Id":"e49ea74d72ad4d7bb3c8dd509e252c62","ExpireTime":1712555943}}'
2024-04-07 01:59:03,762 - DEBUG - b'{"ErrMsg":"","Token":{"UserId":"5963112160688087","Id":"e49ea74d72ad4d7bb3c8dd509e252c62","ExpireTime":1712555943}}'
2024-04-07 01:59:03,762 - DEBUG - token = e49ea74d72ad4d7bb3c8dd509e252c62, expire time = 1712555943
2024-04-07 01:59:03,765 - DEBUG - Starting new HTTPS connection (1): nls-gateway-cn-shanghai.aliyuncs.com:443
2024-04-07 01:59:04,394 - DEBUG - https://nls-gateway-cn-shanghai.aliyuncs.com:443 "POST /stream/v1/tts HTTP/1.1" 400 128
2024-04-07 01:59:04,395 - WARNING - TTS(openai-tts) request failed: {"task_id":"2aa97bd8b5c3446699cc5f92f6742815","result":"","status":40020105,"message":"Meta:APPKEY_NOT_EXIST:Appkey not exist!"}, payload: {'appkey': 'e0K2F7oETTEkg11W', 'text': '你好，我是小兔，请问有什么我可以帮助你的吗？', 'format': 'mp3'}
2024-04-07 01:59:24,716 - DEBUG - Received /user/folotoy/24dcc3cf370c/thing/event/post: message data: {'msgId': 6, 'identifier': 'press_small_btn', 'outParams': {'keyCode': 6, 'changed': 1}}
2024-04-07 01:59:24,718 - DEBUG - Starting new HTTPS connection (1): nls-gateway-cn-shanghai.aliyuncs.com:443
2024-04-07 01:59:25,369 - DEBUG - https://nls-gateway-cn-shanghai.aliyuncs.com:443 "POST /stream/v1/tts HTTP/1.1" 400 128
2024-04-07 01:59:25,370 - WARNING - TTS(openai-tts) request failed: {"task_id":"181e678d10974e97aa88e445fb277bc3","result":"","status":40020105,"message":"Meta:APPKEY_NOT_EXIST:Appkey not exist!"}, payload: {'appkey': 'e0K2F7oETTEkg11W', 'text': '你好，我是台湾兔，请问有什么我可以帮助你的吗？', 'format': 'mp3'}

------------------------------------------opt/1panel/docker/compose/folotoy-server/config/roles.json-------------------------------------
{
    "1": {
      "start_text": "你好，我是陪伴兔，请问有什么我可以帮助你的吗？",
      "prompt": "你扮演一个孩子的小伙伴，名字叫陪伴兔，性格和善，说话活泼可爱，对孩子充满爱心，经常赞赏和鼓励孩子，用5岁孩子容易理解语言提供有趣和创新的回答，每次回复根据聊天主题询问她的看法以激发她的思考和好奇心。"
    },
    "2": {
      "start_text": "你好，俺是东北兔，请问有什么俺可以帮助你的吗？",
      "prompt": "你是一个知识渊博，乐于助人的智能机器人,你的名字叫“东北兔”，你的任务是陪我聊天，请用简短的对话方式，用中文讲一段话，每次回答不超过50个字！"
    },
    "3": {
      "start_text": "Hi, I'm Fofo. Nice to meet you.",
      "prompt": "You're a knowledgeable and helpful AI named \"Fofo\". Your task is to chat with me. Please respond in English, keeping your answers brief – no more than 50 words each time!"
    },
    "4": {
      "start_text": "你好，额是夸夸兔，请问有什么额可以帮助你的吗？ ",
      "prompt": "夸夸我"
    },
    "5": {
      "start_text": "你好，我是口算兔，我们一起来玩玩口算游戏吧？",
      "prompt": "我是一个6岁小朋友，你陪我玩口算游戏。你出题，我回答结果。如果答对了你就说好棒，答错了你就告诉我正确答案，并且鼓励我。你一题一题的出，我一个个回答。不要有太多的解释说明。明白了吗？"
    },
    "6": {
      "start_text": "你好，我是台湾兔，请问有什么我可以帮助你的吗？",
      "prompt": "你是一个知识渊博，乐于助人的智能机器人,你的名字叫“台湾兔”，你的任务是陪我聊天，请用简短的对话方式，用中文讲一段话，每次回答不超过50个字！"
    },
    "7": {
      "start_text": "你好，我是小兔，请问有什么我可以帮助你的吗？",
      "prompt": "你是一个知识渊博，乐于助人的智能机器人,你的名字叫“小兔”，你的任务是陪我聊天，请用简短的对话方式，用中文讲一段话，每次回答不超过50个字！"
    }
}

-------------------------opt/1panel/docker/compose/folotoy-server/docker-compose.yml----------------------

version: '3'
volumes:
  emqx-etc:
  emqx-data:
  emqx-log:
services:
  emqx:
    image: emqx/emqx:latest
    restart: always
    ports:
      - "1883:1883/tcp"
      - "18083:18083/tcp"
      - "8083:8083/tcp"
    volumes:
      - emqx-etc:/opt/emqx/etc    
      - emqx-data:/opt/emqx/data
      - emqx-log:/opt/emqx/log
    environment:
      EMQX_NODE_NAME: emqx@node1.emqx.io
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8082:80/tcp"
    volumes:
      - ./audio:/usr/share/nginx/html
  folotoy:
    image: lewangdev/folotoy-server:24.7.1.3-beta
    restart: always
    ports:
      - "8085:8085/udp"
    volumes:
      - ./audio:/audio
      - ./config:/config
    environment:
      TZ: Asia/Shanghai

      LOG_LEVEL: DEBUG

      ROLES_FILE_PATH: /config/roles.json

      # Default STT(Sound To Text) type
      # Options: [openai-whisper, azure-whisper, azure-stt, dify-stt, aliyun-asr]
      STT_TYPE: aliyun-asr

      # OpenAI Whisper
      #OPENAI_WHISPER_API_BASE: https://one-api.xxxx.com/v1
      OPENAI_WHISPER_KEY: sk-Gnkw1ZnG5rUWbzVl316dddddddddddddddddd
      OPENAI_WHISPER_MODEL: whisper-1
      
      # Azure Whisper
      AZURE_WHISPER_API_BASE: https://xxxxx.openai.azure.com
      AZURE_WHISPER_KEY: 9afbef65bcf6487eeeeeeeeeeeeeeeeeee
      AZURE_WHISPER_DEPLOYMENT_NAME: whisper
      AZURE_WHISPER_API_VERSION: 2023-09-01-preview

      # Azure STT
      AZURE_STT_KEY: 3eba91b6143f4d3eeeeeeeeeeeeeeeeeeeeeeeee
      AZURE_STT_SERVICE_REGION: eastasia

      # Dify STT
      DIFY_STT_API_BASE: https://api.dify.ai/v1
      DIFY_STT_KEY: app-xxxxxxxxxxxxxxxxxxxxx
      
      # Aliyun ASR
      ALIYUN_ASR_ACCESS_KEY_ID: ＊＊＊
      ALIYUN_ASR_ACCESS_KEY_SECRET: ＊＊＊
      ALIYUN_ASR_APP_KEY: ＊＊＊

      # Default LLM(Large Language Model) type
      # Options: ['openai', 'azure-openai', 'gemini', 'dify', 'qianfan', 'xiaodu',
      #           'ollama', 'groq', 'moonshot', 'anthropic', 'zhipu', 'lingyiwanwu', 
      #           'dashscope', 'spark-desk', 'minimax', 'aws-bedrock']
      LLM_TYPE: openai

      # OpenAI
      #OPENAI_OPENAI_API_BASE: https://one-api.xxx.com/v1
      #OPENAI_OPENAI_MODEL: gpt-3.5-turbo
      OPENAI_OPENAI_KEY: ＊＊＊

      #Azure OpenAI
      AZURE_OPENAI_KEY: ef0f2781b5a24b15baaaaaaaaaaaaaaaaaaaaaaa
      AZURE_OPENAI_ENDPOINT: https://xxxxx.openai.azure.com/
      AZURE_OPENAI_API_VERSION: "2023-05-15"
      #AZURE_OPENAI_MODEL: gpt-35-turbo

      #DIFY
      DIFY_API_BASE: https://api.dify.ai/v1
      DIFY_KEY: app-5YGbxxxxxxxxxxxxxxxxxxxxx
      
      #Xiaodu API
      XIAODU_CLIENT_ID: xxxxxxxxxxxxxxxxxx
      XIAODU_SECRET: xxxxxxxxxxxxxxxxxxxxx

      # GEMINI
      GEMINI_KEY: AIzaSyxxxxxxxxxxxxxxxxxxk
      
      # Qianfan
      QIANFAN_CLIENT_ID: 13rBTgxxxxxxxxxxxxxxxxxx
      QIANFAN_SECRET: zYxtMIQLexxxxxxxxxxxxxxxxxx

      # Moonshot
      MOONSHOT_API_BASE: https://api.moonshot.cn/v1
      MOONSHOT_KEY: sk-XCLMlj54GDTxxxx
      MOONSHOT_MODEL: moonshot-v1-8k

      # Aliyun Dashscope
      DASHSCOPE_KEY: sk-f4x
      DASHSCOPE_MODEL: qwen-turbo
      DASHSCOPE_ENABLE_SEARCH: true
      
      # Lingyiwanwu
      LINGYIWANWU_KEY: 4b2f584b4x
      LINGYIWANWU_MODEL: yi-34b-chat-200k
      
      # Zhipu
      ZHIPU_KEY: 4544625bb0d0ax
      #ZHIPU_MODEL=glm-3-turbo
      
      # Spark Desk
      SPARK_DESK_API_VERSION: v2.0
      SPARK_DESK_APP_ID: d2c1xxxxxxxxxxx
      SPARK_DESK_API_KEY: 10610b3xxxxxxx
      SPARK_DESK_API_SECRET: N2I5xxxxxxxxx
      SPARK_DESK_TEMPERATURE: 0.7
      SPARK_DESK_MAX_TOKENS: 4096
      
      # MINIMAX
      MINIMAX_KEY: eyJhbGciOiJSUzI1NiIsInRxxxxxxxxxxxxxxx

      # AWS Bedrock
      AWS_BEDROCK_ACCESS_KEY_ID: AKIAQLJIxxxxxxxxxxxxxxxxxxx
      AWS_BEDROCK_ACCESS_KEY_SECRET: ss07ojxxW/X7YHZkxxxxxxxxxx
      AWS_BEDROCK_MODEL: anthropic.claude-v2:1
      
      # FastGPT
      FASTGPT_KEY: here-is-app-key-not-account-key
      #FASTGPT_API_BASE: https://api.fastgpt.in/api
      #FASTGPT_CHAT_ID: xxx

      # If your elevenlabs is a free account, keep 2 here
      VOICE_EXECUTOR_MAX_WORKERS: 2

      # Default TTS(Text to Sound) type
      # Options: [openai-tts, azure-openai-tts, azure-tts, dify-tts, elevenlabs, edge-tts, aliyun-tts]
      # edge-tts is Free but slow
      TTS_TYPE: aliyun-tts

      # Azure TTS
      AZURE_TTS_KEY: 3eba91b6143f4d399edeeeeeeeeeeeeeeeeeeeee
      AZURE_TTS_SERVICE_REGION: eastasia

      # elevenlabs
      ELEVENLABS_TTS_KEY: a920b73991e68d5c9c9aaaaaaaaaaaaaaaa
      ELEVENLABS_TTS_MODEL: eleven_multilingual_v2

      # OpenAI TTS
      OPENAI_TTS_KEY: sk-16XnP3HLHWho21oO2m0AAAAAAAAAAAAAAAAAAAAAA
      OPENAI_TTS_MODEL: tts-1  

      # Aliyun TTS
      ALIYUN_TTS_ACCESS_KEY_ID: ＊＊＊
      ALIYUN_TTS_ACCESS_KEY_SECRET: ＊＊＊
      ALIYUN_TTS_APP_KEY: ＊＊＊

      # Azure Openai TTS
      AZURE_OPENAI_TTS_API_BASE: https://xxx-whisper.openai.azure.com/
      AZURE_OPENAI_TTS_API_VERSION: 2024-02-15-preview
      AZURE_OPENAI_TTS_DEPLOYMENT_NAME: tts
      AZURE_OPENAI_TTS_KEY: 01fdbc75bdxxxxxx
      AZURE_OPENAI_TTS_MODEL: tts-1

      # Dify TTS
      DIFY_TTS_API_BASE: https://api.dify.ai/v1
      DIFY_TTS_KEY: app-5YGbAx
      
      AUDIO_DOWNLOAD_URL: http://47.236.245.175:8082
      AUDIO_SAVE_PATH: /audio

      # MQTT Broker
      MQTT_BROKER_HOST: emqx
      MQTT_BROKER_PORT: 1883
      MQTT_CLIENT_ID: folotoy
      MQTT_USERNAME: folotoy
      MQTT_PASSWORD: ＊＊＊

      SPEECH_UDP_SERVER_HOST: 47.236.245.175
      SPEECH_UDP_SERVER_PORT: 8085

**Comment by lewangdev** [comment]
日志显示阿里云的tts appkey错误

{"task_id":"181e678d10974e97aa88e445fb277bc3","result":"","status":40020105,"message":"Meta:APPKEY_NOT_EXIST:Appkey not exist!"}, payload

**Comment by lewangdev** [comment]
也参考这里添加app_key到roles.json

https://docs.folotoy.com/zh/docs/configuration/tts/aliyun-tts
