### ISSUE TITLE
[Errno 111] Connection refused，之前配置OK过，最近更换了roles.json路径重新配置后出现这个错误代码

### ISSUE THREAD

**Issue by wgsxsm** [FoloToy/folotoy-server-self-hosting#150]
2024-04-09 09:15:42,386 - INFO - FoloToy Server Version: v23.47.2.5-beta
2024-04-09 09:15:42,405 - ERROR - Run error: [Errno 111] Connection refused
Traceback (most recent call last):
  File "core/folotoy_app.py", line 126, in core.folotoy_app.FolotoyApp.start
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 914, in connect
    return self.reconnect()
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 1044, in reconnect
    sock = self._create_socket_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/socket.py", line 851, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.11/socket.py", line 836, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
2024-04-09 09:15:42,406 - INFO - Sleep 2s to reconnect
2024-04-09 09:15:44,408 - ERROR - Run error: [Errno 111] Connection refused

**Comment by wgsxsm** [comment]
看上去只是warning，算不上error，过一会兔子可以连上了。
