### ISSUE TITLE
报错httpx.HTTPStatusError: Client error '404 Not Found' for url 'https://api.moonshot.cn/v1/chat/completions'

### ISSUE THREAD

**Issue by YunShengzz** [FoloToy/folotoy-server-self-hosting#191]
全部错误是这样的：Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 967, in _request
    response.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/httpx/_models.py", line 761, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '404 Not Found' for url 'https://api.moonshot.cn/v1/chat/completions'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404

**Comment by lewangdev** [comment]
moonshot名称没有设置正确
