### ISSUE TITLE
openai whisper 429

### ISSUE THREAD

**Issue by acondess** [FoloToy/folotoy-server-self-hosting#192]
Request options: {'method': 'post', 'url': '/audio/transcriptions', 'headers': {'Content-Type': 'multipart/form-data'}, 'timeout': 20.0, 'files': [('file', SerializationIterator(index=0, iterator=SerializationIterator(index=0, iterator=<_io.BufferedReader name='/audio/recording-b6afdf6f79f14ef6ba29ccb48d8d6207.wav'>)))], 'json_data': {'model': 'whisper-1', 'language': 'zh', 'prompt': "ok. let's begin.", 'response_format': 'json'}}
2024-06-19 15:56:51 folotoy-1  | 2024-06-19 15:56:51,747 - DEBUG - connect_tcp.started host='api.openai.com' port=443 local_address=None timeout=20.0 socket_options=None
2024-06-19 15:56:51 folotoy-1  | 2024-06-19 15:56:51,767 - DEBUG - connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x7efd9a44a150>
2024-06-19 15:56:51 folotoy-1  | 2024-06-19 15:56:51,767 - DEBUG - start_tls.started ssl_context=<ssl.SSLContext object at 0x7efd9a236b10> server_hostname='api.openai.com' timeout=20.0
2024-06-19 15:56:52 folotoy-1  | 2024-06-19 15:56:52,538 - DEBUG - start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0x7efd985c1050>
2024-06-19 15:56:52 folotoy-1  | 2024-06-19 15:56:52,538 - DEBUG - send_request_headers.started request=<Request [b'POST']>
2024-06-19 15:56:52 folotoy-1  | 2024-06-19 15:56:52,539 - DEBUG - send_request_headers.complete
2024-06-19 15:56:52 folotoy-1  | 2024-06-19 15:56:52,539 - DEBUG - send_request_body.started request=<Request [b'POST']>
2024-06-19 15:56:52 folotoy-1  | 2024-06-19 15:56:52,544 - DEBUG - send_request_body.complete
2024-06-19 15:56:52 folotoy-1  | 2024-06-19 15:56:52,544 - DEBUG - receive_response_headers.started request=<Request [b'POST']>
2024-06-19 15:56:54 folotoy-1  | 2024-06-19 15:56:54,147 - DEBUG - receive_response_headers.complete return_value=(b'HTTP/1.1', 429, b'Too Many Requests', [(b'Date', b'Wed, 19 Jun 2024 07:57:22 GMT'), (b'Content-Type', b'application/json; charset=utf-8'), (b'Content-Length', b'337'), (b'Connection', b'keep-alive'), (b'vary', b'Origin'), (b'x-request-id', b'req_9930b063133383d74ee4e5dfafb11048'), (b'strict-transport-security', b'max-age=15724800; includeSubDomains'), (b'CF-Cache-Status', b'DYNAMIC'), (b'Set-Cookie', b'__cf_bm=1ls_Xcpw9ATv5CRuL3UVW5lynBfaer6TH8a2DQDN1CI-1718783842-1.0.1.1-AzqZAiNHC1o1A_8oSOskKEM3IAR3McGEwNdG0m2klPeovN2Olmbypsze_euH4BDzuZmRmHxzHAn9xXIW4kfAKg; path=/; expires=Wed, 19-Jun-24 08:27:22 GMT; domain=.api.openai.com; HttpOnly; Secure; SameSite=None'), (b'Set-Cookie', b'_cfuvid=CLiUgZhtk86bidil7q2vlPdjdY6g5jQK8C4g5P_.7zs-1718783842429-0.0.1.1-604800000; path=/; domain=.api.openai.com; HttpOnly; Secure; SameSite=None'), (b'Server', b'cloudflare'), (b'CF-RAY', b'8961f7be9c2c7f75-MAA'), (b'alt-svc', b'h3=":443"; ma=86400')])
2024-06-19 15:56:54 folotoy-1  | 2024-06-19 15:56:54,148 - INFO - HTTP Request: POST https://api.openai.com/v1/audio/transcriptions "HTTP/1.1 429 Too Many Requests"
2024-06-19 15:56:54 folotoy-1  | 2024-06-19 15:56:54,148 - DEBUG - receive_response_body.started request=<Request [b'POST']>
2024-06-19 15:56:54 folotoy-1  | 2024-06-19 15:56:54,148 - DEBUG - receive_response_body.complete
2024-06-19 15:56:54 folotoy-1  | 2024-06-19 15:56:54,148 - DEBUG - response_closed.started
2024-06-19 15:56:54 folotoy-1  | 2024-06-19 15:56:54,148 - DEBUG - response_closed.complete
2024-06-19 15:56:54 folotoy-1  | 2024-06-19 15:56:54,148 - DEBUG - HTTP Request: POST https://api.openai.com/v1/audio/transcriptions "429 Too Many Requests"
2024-06-19 15:56:54 folotoy-1  | 2024-06-19 15:56:54,149 - DEBUG - Encountered httpx.HTTPStatusError
2024-06-19 15:56:54 folotoy-1  | Traceback (most recent call last):
2024-06-19 15:56:54 folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 967, in _request
2024-06-19 15:56:54 folotoy-1  |     response.raise_for_status()
2024-06-19 15:56:54 folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/httpx/_models.py", line 761, in raise_for_status
2024-06-19 15:56:54 folotoy-1  |     raise HTTPStatusError(message, request=request, response=self)
2024-06-19 15:56:54 folotoy-1  | httpx.HTTPStatusError: Client error '429 Too Many Requests' for url 'https://api.openai.com/v1/audio/transcriptions'
2024-06-19 15:56:54 folotoy-1  | For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429
2024-06-19 15:56:54 folotoy-1  | 2024-06-19 15:56:54,151 - DEBUG - Retrying due to status code 429
2024-06-19 15:56:54 folotoy-1  | 2024-06-19 15:56:54,151 - DEBUG - 1 retry left
2024-06-19 15:56:54 folotoy-1  | 2024-06-19 15:56:54,151 - INFO - Retrying request to /audio/transcriptions in 0.753795 seconds
2024-06-19 15:56:54 folotoy-1  | 2024-06-19 15:56:54,905 - DEBUG - Request options: {'method': 'post', 'url': '/audio/transcriptions', 'headers': {'Content-Type': 'multipart/form-data'}, 'timeout': 20.0, 'files': [('file', SerializationIterator(index=0, iterator=SerializationIterator(index=0, iterator=<_io.BufferedReader name='/audio/recording-b6afdf6f79f14ef6ba29ccb48d8d6207.wav'>)))], 'json_data': {'model': 'whisper-1', 'language': 'zh', 'prompt': "ok. let's begin.", 'response_format': 'json'}}

**Comment by lewangdev** [comment]
是免费的账户吗？需要充值
