### ISSUE TITLE
改为豆包后报错

### ISSUE THREAD

**Issue by YunShengzz** [FoloToy/folotoy-server-self-hosting#198]
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/volcenginesdkarkruntime/_base_client.py", line 448, in _request
    response.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/httpx/_models.py", line 761, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '401 Unauthorized' for url 'https://ark.cn-beijing.volces.com/api/v3/chat/completions'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401
![image](https://github.com/FoloToy/folotoy-server-self-hosting/assets/171758486/96f8d66c-b7d9-4366-982b-eaaa35d30314)
我的配置是这样的，下面两行key我没有截图但是都填写正确了，是我的模型名字填写的不对吗

**Comment by lewangdev** [comment]
模型名字错了

**Comment by YunShengzz** [comment]
是我的环境变量中名字错误了，还是roles配置中写错了


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年06月21日 22:24 |
| 收件人 | FoloToy/folotoy-server-self-hosting ***@***.***> |
| 抄送人 | YunShengzz ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [FoloToy/folotoy-server-self-hosting] 改为豆包后报错 (Issue #198) |

模型名字错了

**Comment by lewangdev** [comment]
model_name登录自己的火山账号之后才能看到

**Comment by lewangdev** [comment]
不是doubao-lite-4k

**Comment by YunShengzz** [comment]
好的谢谢，正常来说环境变量里面的name和roles里面的name是一样的对吧，我只不过是名字写错了


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年06月22日 15:33 |
| 收件人 | FoloToy/folotoy-server-self-hosting ***@***.***> |
| 抄送人 | YunShengzz ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [FoloToy/folotoy-server-self-hosting] 改为豆包后报错 (Issue #198) |

不是doubao-lite-4k
