### ISSUE TITLE
火火兔（更换电路板）无法连接到连接自建服务器（阿里云服务器 Ubuntu）

### ISSUE THREAD

**Issue by tonyyang2020-web** [FoloToy/folotoy-server-self-hosting#206]
folotoy-server日志追踪，出现以下错误：
2024-07-07 21:19:26,003 - INFO - FoloToy Server Version: v24.25.6.1-beta
2024-07-07 21:19:26,007 - INFO - Connected to MQTT Broker(emqx:1883)!
2024-07-07 21:19:26,007 - INFO - Speech server started(0.0.0.0:8085/udp)
2024-07-07 21:22:18,601 - INFO - FoloToy Server Version: v24.25.6.1-beta
2024-07-07 21:22:18,604 - ERROR - Run error: [Errno 111] Connection refused
Traceback (most recent call last):
  File "core/folotoy_app.py", line 141, in core.folotoy_app.FolotoyApp.start
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 1429, in connect
    return self.reconnect()
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 1592, in reconnect
    self._sock = self._create_socket()
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 4598, in _create_socket
    sock = self._create_socket_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 4623, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/socket.py", line 851, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.11/socket.py", line 836, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
2024-07-07 21:22:18,607 - INFO - Sleep 2s to reconnect to emqx:1883
2024-07-07 21:22:20,609 - ERROR - Run error: [Errno 111] Connection refused
Traceback (most recent call last):
  File "core/folotoy_app.py", line 141, in core.folotoy_app.FolotoyApp.start
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 1429, in connect
    return self.reconnect()
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 1592, in reconnect
    self._sock = self._create_socket()
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 4598, in _create_socket
    sock = self._create_socket_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 4623, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/socket.py", line 851, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.11/socket.py", line 836, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
2024-07-07 21:22:20,610 - INFO - Sleep 2s to reconnect to emqx:1883
2024-07-07 21:22:22,612 - INFO - Speech server started(0.0.0.0:8085/udp)
2024-07-07 21:22:22,617 - INFO - Connected to MQTT Broker(emqx:1883)!
![安全组](https://github.com/FoloToy/folotoy-server-self-hosting/assets/174870578/5981a7df-7831-40e9-88d2-a0fc7fc04792)
[roles.json](https://github.com/user-attachments/files/16119504/roles.json)
[docker-compose-yml.txt](https://github.com/user-attachments/files/16119517/docker-compose-yml.txt)

**Comment by lewangdev** [comment]
安全组的端口没全部添加
