### ISSUE TITLE
ConnectionRefusedError: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by JiajunBernoulli** [FoloToy/folotoy-server-self-hosting#210]
一直正常启动，一次重启后突然报错
```
2024-07-21 18:07:39,387 - ERROR - Run error: [Errno 111] Connection refused
2024-07-21 18:07:39 Traceback (most recent call last):
2024-07-21 18:07:39   File "core/folotoy_app.py", line 141, in core.folotoy_app.FolotoyApp.start
2024-07-21 18:07:39   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 1429, in connect
2024-07-21 18:07:39     return self.reconnect()
2024-07-21 18:07:39            ^^^^^^^^^^^^^^^^
2024-07-21 18:07:39   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 1592, in reconnect
2024-07-21 18:07:39     self._sock = self._create_socket()
2024-07-21 18:07:39                  ^^^^^^^^^^^^^^^^^^^^^
2024-07-21 18:07:39   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 4598, in _create_socket
2024-07-21 18:07:39     sock = self._create_socket_connection()
2024-07-21 18:07:39            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-21 18:07:39   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 4623, in _create_socket_connection
2024-07-21 18:07:39     return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
2024-07-21 18:07:39            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-21 18:07:39   File "/usr/local/lib/python3.11/socket.py", line 851, in create_connection
2024-07-21 18:07:39     raise exceptions[0]
2024-07-21 18:07:39   File "/usr/local/lib/python3.11/socket.py", line 836, in create_connection
2024-07-21 18:07:39     sock.connect(sa)
2024-07-21 18:07:39 ConnectionRefusedError: [Errno 111] Connection refused
2024-07-21 18:07:39 2024-07-21 18:07:39,389 - INFO - Sleep 2s to reconnect to emqx:1883
2024-07-21 18:07:41 2024-07-21 18:07:41,391 - ERROR - Run error: [Errno 111] Connection refused
2024-07-21 18:07:41 Traceback (most recent call last):
2024-07-21 18:07:41   File "core/folotoy_app.py", line 141, in core.folotoy_app.FolotoyApp.start
2024-07-21 18:07:41   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 1429, in connect
2024-07-21 18:07:41     return self.reconnect()
2024-07-21 18:07:41            ^^^^^^^^^^^^^^^^
2024-07-21 18:07:41   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 1592, in reconnect
2024-07-21 18:07:41     self._sock = self._create_socket()
2024-07-21 18:07:41                  ^^^^^^^^^^^^^^^^^^^^^
2024-07-21 18:07:41   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 4598, in _create_socket
2024-07-21 18:07:41     sock = self._create_socket_connection()
2024-07-21 18:07:41            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-21 18:07:41   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 4623, in _create_socket_connection
2024-07-21 18:07:41     return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
2024-07-21 18:07:41            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-21 18:07:41   File "/usr/local/lib/python3.11/socket.py", line 851, in create_connection
2024-07-21 18:07:41     raise exceptions[0]
2024-07-21 18:07:41   File "/usr/local/lib/python3.11/socket.py", line 836, in create_connection
2024-07-21 18:07:41     sock.connect(sa)
2024-07-21 18:07:41 ConnectionRefusedError: [Errno 111] Connection refused
```
确认了端口都没有被占用，应该如何排查呢？
![image](https://github.com/user-attachments/assets/813360af-a011-49ad-b4d6-94bc0c1d8102)

**Comment by lewangdev** [comment]
稍等一下就会正常，emqx启动比较慢，或者自己改一下配置，然emqx启动之后再启动folotoy-server

**Comment by JiajunBernoulli** [comment]
的确，不影响正常运行

Close #210

**Comment by JiajunBernoulli** [comment]
感谢解答！
