### ISSUE TITLE
报错,烦请看看,使用azure-stt

### ISSUE THREAD

**Issue by last2004** [FoloToy/folotoy-server-self-hosting#47]
本地黑裙NAS,使用azure的stt,openai,tts
配置文件如下:
```
version: '3'
services:
  emqx:
    image: emqx/emqx:latest
    restart: always
    ports:
      - "1883:1883/tcp"
      - "18083:18083/tcp"
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8082:80/tcp"
    volumes:
      - ./audio:/usr/share/nginx/html
  folotoy:
    image: lewangdev/folotoy-server:latest
    restart: always
    depends_on:
      emqx:
          condition: service_started
      nginx:
          condition: service_started
    ports:
      - "8085:8085/udp"
    volumes:
      - ./audio:/audio
      - ./roles.json:/roles.json
    environment:
      LOG_LEVEL: DEBUG
      ROLES_FILE_PATH: /roles.json
      # Default STT(Sound To Text) type
      # Options: [openai-whisper, azure-whisper, azure-stt]
      STT_TYPE: azure-stt

      # OpenAI Whisper
      #OPENAI_WHISPER_API_BASE: https://one-api.xxxx.com/v1
      OPENAI_WHISPER_KEY: sk-Gnkw1ZnG5rUWbzVl316dddddddddddddddddd
      OPENAI_WHISPER_MODEL: whisper-1
      
      # Azure Whisper
      AZURE_WHISPER_API_BASE: https://xxxxx.openai.azure.com
      AZURE_WHISPER_KEY: 9afbef65bcf6487eeeeeeeeeeeeeeeeeee
      AZURE_WHISPER_DEPLOYMENT_NAME: whisper
      AZURE_WHISPER_API_VERSION: 2023-09-01-preview

      # Azure STT
      AZURE_STT_KEY: b9f8a7b5c49e498f87e523d068xxx[此处隐去,与TTS一样]
      AZURE_STT_SERVICE_REGION: koreacentral

      # Default LLM(Large Language Model) type
      # Options: [openai, azure-openai]
      LLM_TYPE: azure-openai

      # OpenAI
      #OPENAI_OPENAI_API_BASE: https://one-api.xxx.com/v1
      OPENAI_OPENAI_KEY: sk-5N8F5VXsa7oOZI8Q874601110AAAAAAAAAAAAAAAAAAAAAA

      #Azure OpenAI
      AZURE_OPENAI_KEY: 0c6d63a0af864b98ac76c72a6c7xxx[此处隐去]
      AZURE_OPENAI_ENDPOINT: https://folotoy.openai.azure.com/
      AZURE_OPENAI_VERSION: "2023-07-01-preview"

      #Baidu YIYAN API
      #LLM_TYPE: yiyan
      YIYAN_CLIENT_ID: xxxxxxxxxxxxxxxxxx
      YIYAN_SECRET: xxxxxxxxxxxxxxxxxxxxx

      # If your elevenlabs is a free account, keep 2 here
      VOICE_EXECUTOR_MAX_WORKERS: 2

      # Default TTS(Text to Sound) type
      # Options: [edge-tts, azure-tts, elevenlabs]
      # edge-tts is Free but slow
      TTS_TYPE: edge-tts

      # Azure TTS
      AZURE_TTS_KEY: b9f8a7b5c49e498f87e523d068xxx[此处隐去,与STT一样]
      AZURE_TTS_SERVICE_REGION: koreacentral

      # elevenlabs
      ELEVENLABS_TTS_KEY: a920b73991e68d5c9c9aaaaaaaaaaaaaaaa
      ELEVENLABS_TTS_MODEL: eleven_multilingual_v2

      AUDIO_DOWNLOAD_URL: http://192.168.1.254:8082
      AUDIO_SAVE_PATH: /audio

      # MQTT Broker
      MQTT_BROKER_HOST: emqx
      MQTT_BROKER_PORT: 1883
      MQTT_CLIENT_ID: folotoy
      MQTT_USERNAME: folotoy
      MQTT_PASSWORD: folotoy

      SPEECH_UDP_SERVER_HOST: 192.168.1.253
      SPEECH_UDP_SERVER_PORT: 8085
```

错误如下:
```
2023-10-26 14:23:41,174 - DEBUG - Current dkey=a0a3b3182450 role=1
2023-10-26 14:23:41,175 - DEBUG - STT type: azure-stt
2023-10-26 14:23:41,230 - ERROR - Record error: Traceback (most recent call last):
  File "core/speech_server.py", line 194, in core.speech_server.SpeechServer.write_wav
  File "sdk/stt.py", line 27, in sdk.stt.SttSdk.transcribe
  File "sdk/stt.py", line 49, in sdk.stt.SttSdk.azure_stt
  File "sdk/stt_sdk/azure_stt.py", line 21, in sdk.stt_sdk.azure_stt.AzureSttEngine.sound_to_text
  File "/usr/local/lib/python3.11/site-packages/azure/cognitiveservices/speech/speech.py", line 187, in speech_recognition_language
    self.set_property(PropertyId.SpeechServiceConnection_RecoLanguage, language)
  File "/usr/local/lib/python3.11/site-packages/azure/cognitiveservices/speech/speech.py", line 128, in set_property
    self._properties.set_property(property_id, value)
  File "/usr/local/lib/python3.11/site-packages/azure/cognitiveservices/speech/properties.py", line 29, in set_property
    _call_hr_fn(fn=_sdk_lib.property_bag_set_string, *[self._handle, ctypes.c_int(property_id.value), None, c_value])
  File "/usr/local/lib/python3.11/site-packages/azure/cognitiveservices/speech/interop.py", line 62, in _call_hr_fn
    _raise_if_failed(hr)
  File "/usr/local/lib/python3.11/site-packages/azure/cognitiveservices/speech/interop.py", line 56, in _raise_if_failed
    raise RuntimeError(hr)
RuntimeError: 5
Traceback (most recent call last):
  File "core/speech_server.py", line 194, in core.speech_server.SpeechServer.write_wav
  File "sdk/stt.py", line 27, in sdk.stt.SttSdk.transcribe
  File "sdk/stt.py", line 49, in sdk.stt.SttSdk.azure_stt
  File "sdk/stt_sdk/azure_stt.py", line 21, in sdk.stt_sdk.azure_stt.AzureSttEngine.sound_to_text
  File "/usr/local/lib/python3.11/site-packages/azure/cognitiveservices/speech/speech.py", line 187, in speech_recognition_language
    self.set_property(PropertyId.SpeechServiceConnection_RecoLanguage, language)
  File "/usr/local/lib/python3.11/site-packages/azure/cognitiveservices/speech/speech.py", line 128, in set_property
    self._properties.set_property(property_id, value)
  File "/usr/local/lib/python3.11/site-packages/azure/cognitiveservices/speech/properties.py", line 29, in set_property
    _call_hr_fn(fn=_sdk_lib.property_bag_set_string, *[self._handle, ctypes.c_int(property_id.value), None, c_value])
  File "/usr/local/lib/python3.11/site-packages/azure/cognitiveservices/speech/interop.py", line 62, in _call_hr_fn
    _raise_if_failed(hr)
  File "/usr/local/lib/python3.11/site-packages/azure/cognitiveservices/speech/interop.py", line 56, in _raise_if_failed
    raise RuntimeError(hr)
RuntimeError: 5
```

**Comment by lewangdev** [comment]
看日志是azure的库报错了。azure的库可能不支持黑裙

**Comment by last2004** [comment]
是黑裙 版本 `版本 7.2-64570`
azure 的库对系统和CPU架构有要求?
