### ISSUE TITLE
使用one-api, 并且使用chatgpt-web测通了api key,但是folotoy无法连接

### ISSUE THREAD

**Issue by skstudying** [FoloToy/folotoy-server-self-hosting#67]
继昨天docker内无代理的问题，现在注册使用了one-api， 可以不挂代理通过chatgpt-web项目调用api-key，但是在folotoy仍然无法正常对话。

以下是问题发生的logs
```
2023-11-14T10:06:40.625605300Z 2023-11-14 10:06:40,625 - DEBUG - Received frame type: b'\x02'
2023-11-14T10:06:40.626173715Z 2023-11-14 10:06:40,626 - DEBUG - Recording file created: /audio/recording-c987af7667d64b8180ca90541fb5c763.wav
2023-11-14T10:06:40.627137862Z 2023-11-14 10:06:40,627 - DEBUG - Current dkey=08d1f9c69348 role=7
2023-11-14T10:06:40.627591463Z 2023-11-14 10:06:40,627 - DEBUG - STT type: openai-whisper
2023-11-14T10:06:40.630497727Z 2023-11-14 10:06:40,630 - DEBUG - message='Request to OpenAI API' method=post path=https://www.oneapi.cc/audio/transcriptions
2023-11-14T10:06:40.631009077Z 2023-11-14 10:06:40,630 - DEBUG - api_version=None data='{\'model\': \'whisper-1\', \'prompt\': "ok. let\'s begin.", \'response_format\': \'json\', \'language\': \'zh\'}' message='Post details'
2023-11-14T10:06:40.631671879Z 2023-11-14 10:06:40,631 - DEBUG - Converted retries value: 2 -> Retry(total=2, connect=None, read=None, redirect=None, status=None)
2023-11-14T10:06:40.633864437Z 2023-11-14 10:06:40,633 - DEBUG - Starting new HTTPS connection (1): www.oneapi.cc:443
2023-11-14T10:06:41.667561093Z 2023-11-14 10:06:41,663 - DEBUG - https://www.oneapi.cc:443 "POST /audio/transcriptions HTTP/1.1" 200 518
2023-11-14T10:06:41.667618463Z 2023-11-14 10:06:41,664 - DEBUG - message='OpenAI API response' path=https://www.oneapi.cc/audio/transcriptions processing_ms=None request_id=None response_code=200
2023-11-14T10:06:41.667623703Z 2023-11-14 10:06:41,666 - ERROR - LLM error: Traceback (most recent call last):
2023-11-14T10:06:41.667627216Z   File "/usr/local/lib/python3.11/site-packages/openai/api_requestor.py", line 765, in _interpret_response_line
2023-11-14T10:06:41.667630395Z     data = json.loads(rbody)
2023-11-14T10:06:41.667633610Z            ^^^^^^^^^^^^^^^^^
2023-11-14T10:06:41.667636434Z   File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
2023-11-14T10:06:41.667639335Z     return _default_decoder.decode(s)
2023-11-14T10:06:41.667641879Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-11-14T10:06:41.667644439Z   File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
2023-11-14T10:06:41.667647108Z     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
2023-11-14T10:06:41.667649746Z                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-11-14T10:06:41.667652366Z   File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
2023-11-14T10:06:41.667655085Z     raise JSONDecodeError("Expecting value", s, err.value) from None
2023-11-14T10:06:41.667657820Z json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-11-14T10:06:41.667660588Z
2023-11-14T10:06:41.667663463Z The above exception was the direct cause of the following exception:
2023-11-14T10:06:41.667666153Z
2023-11-14T10:06:41.667679291Z Traceback (most recent call last):
2023-11-14T10:06:41.667682253Z   File "core/speech_server.py", line 236, in core.speech_server.SpeechServer.write_wav
2023-11-14T10:06:41.667699187Z   File "sdk/stt.py", line 21, in sdk.stt.SttSdk.transcribe
2023-11-14T10:06:41.667702374Z   File "sdk/stt.py", line 22, in sdk.stt.SttSdk.transcribe
2023-11-14T10:06:41.667705087Z   File "sdk/stt.py", line 46, in sdk.stt.SttSdk.openai_whisper
2023-11-14T10:06:41.667707860Z   File "/usr/local/lib/python3.11/site-packages/openai/api_resources/audio.py", line 72, in transcribe
2023-11-14T10:06:41.667710609Z     response, _, api_key = requestor.request("post", url, files=files, params=data)
2023-11-14T10:06:41.667713365Z                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-11-14T10:06:41.667716068Z   File "/usr/local/lib/python3.11/site-packages/openai/api_requestor.py", line 299, in request
2023-11-14T10:06:41.667718855Z     resp, got_stream = self._interpret_response(result, stream)
2023-11-14T10:06:41.667721507Z                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-11-14T10:06:41.667724209Z   File "/usr/local/lib/python3.11/site-packages/openai/api_requestor.py", line 710, in _interpret_response
2023-11-14T10:06:41.667728273Z     self._interpret_response_line(
2023-11-14T10:06:41.667731050Z   File "/usr/local/lib/python3.11/site-packages/openai/api_requestor.py", line 767, in _interpret_response_line
2023-11-14T10:06:41.667733847Z     raise error.APIError(
2023-11-14T10:06:41.667736678Z openai.error.APIError: HTTP code 200 from API (<!doctype html><html lang="en"><head><meta charset="utf-8"/><link rel="icon" href="logo.png"/><meta name="viewport" content="width=device-width,initial-scale=1"/><meta name="theme-color" content="#ffffff"/><meta name="description" content="OpenAI 接口聚合管理，支持多种渠道包括 Azure，可用于二次分发管理 key，仅单可执行文件，已打包好 Docker 镜像，一键部署，开箱即用"/><title>One API</title><script defer="defer" src="/static/js/main.e2cfdad3.js"></script><link href="/static/css/main.54631fc9.css" rel="stylesheet"></head><body><noscript>You need to enable JavaScript to run this app.</noscript><div id="root"></div></body></html>)
2023-11-14T10:06:41.667755737Z Traceback (most recent call last):
2023-11-14T10:06:41.667759115Z   File "/usr/local/lib/python3.11/site-packages/openai/api_requestor.py", line 765, in _interpret_response_line
2023-11-14T10:06:41.667761832Z     data = json.loads(rbody)
2023-11-14T10:06:41.667764541Z            ^^^^^^^^^^^^^^^^^
2023-11-14T10:06:41.667767052Z   File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
2023-11-14T10:06:41.667769719Z     return _default_decoder.decode(s)
2023-11-14T10:06:41.667772226Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-11-14T10:06:41.667774890Z   File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
2023-11-14T10:06:41.667777541Z     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
2023-11-14T10:06:41.667784576Z                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-11-14T10:06:41.667787208Z   File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
2023-11-14T10:06:41.667789972Z     raise JSONDecodeError("Expecting value", s, err.value) from None
2023-11-14T10:06:41.667792594Z json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-11-14T10:06:41.667795219Z
2023-11-14T10:06:41.667797624Z The above exception was the direct cause of the following exception:
2023-11-14T10:06:41.667800351Z
2023-11-14T10:06:41.667802780Z Traceback (most recent call last):
2023-11-14T10:06:41.667805544Z   File "core/speech_server.py", line 236, in core.speech_server.SpeechServer.write_wav
2023-11-14T10:06:41.667808246Z   File "sdk/stt.py", line 21, in sdk.stt.SttSdk.transcribe
2023-11-14T10:06:41.667810945Z   File "sdk/stt.py", line 22, in sdk.stt.SttSdk.transcribe
2023-11-14T10:06:41.667813526Z   File "sdk/stt.py", line 46, in sdk.stt.SttSdk.openai_whisper
2023-11-14T10:06:41.672264899Z   File "/usr/local/lib/python3.11/site-packages/openai/api_resources/audio.py", line 72, in transcribe
2023-11-14T10:06:41.672290791Z     response, _, api_key = requestor.request("post", url, files=files, params=data)
2023-11-14T10:06:41.672295556Z                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-11-14T10:06:41.672298688Z   File "/usr/local/lib/python3.11/site-packages/openai/api_requestor.py", line 299, in request
2023-11-14T10:06:41.672301875Z     resp, got_stream = self._interpret_response(result, stream)
2023-11-14T10:06:41.672304917Z                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-11-14T10:06:41.672307798Z   File "/usr/local/lib/python3.11/site-packages/openai/api_requestor.py", line 710, in _interpret_response
2023-11-14T10:06:41.672310634Z     self._interpret_response_line(
2023-11-14T10:06:41.672313419Z   File "/usr/local/lib/python3.11/site-packages/openai/api_requestor.py", line 767, in _interpret_response_line
2023-11-14T10:06:41.672316260Z     raise error.APIError(
2023-11-14T10:06:41.672319237Z openai.error.APIError: HTTP code 200 from API (<!doctype html><html lang="en"><head><meta charset="utf-8"/><link rel="icon" href="logo.png"/><meta name="viewport" content="width=device-width,initial-scale=1"/><meta name="theme-color" content="#ffffff"/><meta name="description" content="OpenAI 接口聚合管理，支持多种渠道包括 Azure，可用于二次分发管理 key，仅单可执行文件，已打包好 Docker 镜像，一键部署，开箱即用"/><title>One API</title><script defer="defer" src="/static/js/main.e2cfdad3.js"></script><link href="/static/css/main.54631fc9.css" rel="stylesheet"></head><body><noscript>You need to enable JavaScript to run this app.</noscript><div id="root"></div></body></html>)
2023-11-14T10:06:41.674511851Z 2023-11-14 10:06:41,674 - DEBUG - Publish topic: /user/folotoy/08d1f9c69348/thing/command/call, msg: {"msgId": 2, "identifier": "audioplay_cmd", "inputParams": {"recordingId": 4, "total": 0}}
2023-11-14T10:06:43.646988677Z 2023-11-14 10:06:43,646 - DEBUG - Received /user/folotoy/08d1f9c69348/thing/command/callAck: message data: {'msgId': 2, 'identifier': 'audioplay_cmd', 'result': 1}
2023-11-14T10:06:43.647025262Z 2023-11-14 10:06:43,646 - DEBUG - Command call ack: True, topic_tokens: {'#': [], '+': ['08d1f9c69348']}
```

**Comment by skstudying** [comment]
增加后还是不行
这是现在的logs
```
2023-11-14T10:39:06.174373321Z 2023-11-14 10:39:06,173 - DEBUG - Received frame type: b'\x02'
2023-11-14T10:39:06.174384574Z 2023-11-14 10:39:06,174 - DEBUG - Recording file created: /audio/recording-d5c8d6b57ebf42d88fb3cae7cfa0edb3.wav
2023-11-14T10:39:06.175763652Z 2023-11-14 10:39:06,175 - DEBUG - Current dkey=08d1f9c69348 role=7
2023-11-14T10:39:06.175775256Z 2023-11-14 10:39:06,175 - DEBUG - STT type: openai-whisper
2023-11-14T10:39:06.178755639Z 2023-11-14 10:39:06,178 - DEBUG - message='Request to OpenAI API' method=post path=https://www.oneapi.cc/v1/audio/transcriptions
2023-11-14T10:39:06.179246974Z 2023-11-14 10:39:06,179 - DEBUG - api_version=None data='{\'model\': \'whisper-1\', \'prompt\': "ok. let\'s begin.", \'response_format\': \'json\', \'language\': \'zh\'}' message='Post details'
2023-11-14T10:39:06.179826544Z 2023-11-14 10:39:06,179 - DEBUG - Converted retries value: 2 -> Retry(total=2, connect=None, read=None, redirect=None, status=None)
2023-11-14T10:39:06.181867531Z 2023-11-14 10:39:06,181 - DEBUG - Starting new HTTPS connection (1): www.oneapi.cc:443
2023-11-14T10:39:07.223105176Z 2023-11-14 10:39:07,222 - DEBUG - https://www.oneapi.cc:443 "POST /v1/audio/transcriptions HTTP/1.1" 503 155
2023-11-14T10:39:07.225187054Z 2023-11-14 10:39:07,223 - DEBUG - message='OpenAI API response' path=https://www.oneapi.cc/v1/audio/transcriptions processing_ms=None request_id=None response_code=503
2023-11-14T10:39:07.227669715Z 2023-11-14 10:39:07,227 - DEBUG - Publish topic: /user/folotoy/08d1f9c69348/thing/command/call, msg: {"msgId": 2, "identifier": "audioplay_cmd", "inputParams": {"recordingId": 6, "total": 0}}
2023-11-14T10:39:07.229644266Z 2023-11-14 10:39:07,228 - ERROR - LLM error: Traceback (most recent call last):
2023-11-14T10:39:07.229661624Z   File "core/speech_server.py", line 236, in core.speech_server.SpeechServer.write_wav
2023-11-14T10:39:07.229690289Z   File "sdk/stt.py", line 21, in sdk.stt.SttSdk.transcribe
2023-11-14T10:39:07.229695457Z   File "sdk/stt.py", line 22, in sdk.stt.SttSdk.transcribe
2023-11-14T10:39:07.229700193Z   File "sdk/stt.py", line 46, in sdk.stt.SttSdk.openai_whisper
2023-11-14T10:39:07.229704738Z   File "/usr/local/lib/python3.11/site-packages/openai/api_resources/audio.py", line 72, in transcribe
2023-11-14T10:39:07.229709735Z     response, _, api_key = requestor.request("post", url, files=files, params=data)
2023-11-14T10:39:07.229714384Z                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-11-14T10:39:07.229718939Z   File "/usr/local/lib/python3.11/site-packages/openai/api_requestor.py", line 299, in request
2023-11-14T10:39:07.229723559Z     resp, got_stream = self._interpret_response(result, stream)
2023-11-14T10:39:07.229727958Z                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-11-14T10:39:07.229732418Z   File "/usr/local/lib/python3.11/site-packages/openai/api_requestor.py", line 710, in _interpret_response
2023-11-14T10:39:07.229737290Z     self._interpret_response_line(
2023-11-14T10:39:07.229741937Z   File "/usr/local/lib/python3.11/site-packages/openai/api_requestor.py", line 755, in _interpret_response_line
2023-11-14T10:39:07.229746936Z     raise error.ServiceUnavailableError(
2023-11-14T10:39:07.229766814Z openai.error.ServiceUnavailableError: The server is overloaded or not ready yet.
2023-11-14T10:39:07.229771704Z Traceback (most recent call last):
2023-11-14T10:39:07.229776056Z   File "core/speech_server.py", line 236, in core.speech_server.SpeechServer.write_wav
2023-11-14T10:39:07.229780614Z   File "sdk/stt.py", line 21, in sdk.stt.SttSdk.transcribe
2023-11-14T10:39:07.229784859Z   File "sdk/stt.py", line 22, in sdk.stt.SttSdk.transcribe
2023-11-14T10:39:07.229789268Z   File "sdk/stt.py", line 46, in sdk.stt.SttSdk.openai_whisper
2023-11-14T10:39:07.229793974Z   File "/usr/local/lib/python3.11/site-packages/openai/api_resources/audio.py", line 72, in transcribe
2023-11-14T10:39:07.229798823Z     response, _, api_key = requestor.request("post", url, files=files, params=data)
2023-11-14T10:39:07.229803750Z                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-11-14T10:39:07.229821391Z   File "/usr/local/lib/python3.11/site-packages/openai/api_requestor.py", line 299, in request
2023-11-14T10:39:07.229826465Z     resp, got_stream = self._interpret_response(result, stream)
2023-11-14T10:39:07.229847280Z                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-11-14T10:39:07.229852855Z   File "/usr/local/lib/python3.11/site-packages/openai/api_requestor.py", line 710, in _interpret_response
2023-11-14T10:39:07.229856857Z     self._interpret_response_line(
2023-11-14T10:39:07.229860735Z   File "/usr/local/lib/python3.11/site-packages/openai/api_requestor.py", line 755, in _interpret_response_line
2023-11-14T10:39:07.229864429Z     raise error.ServiceUnavailableError(
2023-11-14T10:39:07.229868073Z openai.error.ServiceUnavailableError: The server is overloaded or not ready yet.
2023-11-14T10:39:07.856918476Z 2023-11-14 10:39:07,856 - DEBUG - Received /user/folotoy/08d1f9c69348/thing/command/callAck: message data: {'msgId': 2, 'identifier': 'audioplay_cmd', 'result': 1}
2023-11-14T10:39:07.857604745Z 2023-11-14 10:39:07,857 - DEBUG - Command call ack: True, topic_tokens: {'#': [], '+': ['08d1f9c69348']}

```

**Comment by skstudying** [comment]
这是当前的配置
```
version: '3'
services:
  emqx:
    image: emqx/emqx:latest
    restart: always
    ports:
      - "1883:1883/tcp"
      - "18083:18083/tcp"
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8082:80/tcp"
    volumes:
      - ./audio:/usr/share/nginx/html
  folotoy:
    image: lewangdev/folotoy-server:latest
    restart: always
    depends_on:
      emqx:
          condition: service_started
      nginx:
          condition: service_started
    ports:
      - "8085:8085/udp"
    volumes:
      - ./audio:/audio
      - ./roles.json:/roles.json
    environment:
      LOG_LEVEL: DEBUG

      ROLES_FILE_PATH: /roles.json

      # Default STT(Sound To Text) type
      # Options: [openai-whisper, azure-whisper, azure-stt]
      STT_TYPE: openai-whisper

      # OpenAI Whisper
      OPENAI_WHISPER_API_BASE: https://www.oneapi.cc/v1
      OPENAI_WHISPER_KEY: sk-DexTztE8qgI7xr1b98Ac03C5AbCe406
      OPENAI_WHISPER_MODEL: whisper-1
      
      # Azure Whisper
      AZURE_WHISPER_API_BASE: https://xxxxx.openai.azure.com
      AZURE_WHISPER_KEY: 9afbef65bcf6487eeeeeeeeeeeeeeeeeee
      AZURE_WHISPER_DEPLOYMENT_NAME: whisper
      AZURE_WHISPER_API_VERSION: 2023-09-01-preview

      # Azure STT
      AZURE_STT_KEY: 3eba91b6143f4d3eeeeeeeeeeeeeeeeeeeeeeeee
      AZURE_STT_SERVICE_REGION: eastasia

      # Default LLM(Large Language Model) type
      # Options: [openai, azure-openai]
      LLM_TYPE: openai

      # OpenAI
      OPENAI_OPENAI_API_BASE: https://www.oneapi.cc/v1
      OPENAI_OPENAI_KEY: sk-DexTztE8qgI7xr1b98Ac03C5AbCe406

      #Azure OpenAI
      AZURE_OPENAI_KEY: ef0f2781b5a24b15baaaaaaaaaaaaaaaaaaaaaaa
      AZURE_OPENAI_ENDPOINT: https://xxxxx.openai.azure.com/
      AZURE_OPENAI_VERSION: "2023-05-15"

      #Baidu YIYAN API
      #LLM_TYPE: yiyan
      YIYAN_CLIENT_ID: xxxxxxxxxxxxxxxxxx
      YIYAN_SECRET: xxxxxxxxxxxxxxxxxxxxx

      # If your elevenlabs is a free account, keep 2 here
      VOICE_EXECUTOR_MAX_WORKERS: 2

      # Default TTS(Text to Sound) type
      # Options: [edge-tts, azure-tts, elevenlabs]
      # edge-tts is Free but slow
      TTS_TYPE: edge-tts

      # Azure TTS
      AZURE_TTS_KEY: 3eba91b6143f4d399edeeeeeeeeeeeeeeeeeeeee
      AZURE_TTS_SERVICE_REGION: eastasia

      # elevenlabs
      ELEVENLABS_TTS_KEY: d320e49fd90344e940a
      ELEVENLABS_TTS_MODEL: eleven_multilingual_v2

      AUDIO_DOWNLOAD_URL: http://120.24.194.182:8082
      AUDIO_SAVE_PATH: /audio

      # MQTT Broker
      MQTT_BROKER_HOST: emqx
      MQTT_BROKER_PORT: 1883
      MQTT_CLIENT_ID: folotoy
      MQTT_USERNAME: folotoy
      MQTT_PASSWORD: folotoy

      SPEECH_UDP_SERVER_HOST: 120.24.194.182
      SPEECH_UDP_SERVER_PORT: 8085

```

**Comment by lewangdev** [comment]
one-api 配置了 whisper-1 模型了没？

**Comment by skstudying** [comment]
已解决。

**问题1：需要oneapi也要保持python的调用格式，API_BASE记得带 /v1**

**问题2：查查自己的oneapi是否支持whisper-1和openai-tts的调用（截至05/11/2023, oneapi还不支持openai-tts)**
可以通过指令 
·curl curl https://${YOUR_ONEAPI_URL}/v1/models   -H 'Authorization: Bearer sk-AKFjvSMpTFufkVgQXXXXXXXXXXXXXX'· 
来查询自己的oneapi支持哪些models
